exportedModules = [
	// TODO: not found if no broadcast
	["broadcastembed", (e) => e.bordered_container],
	["broadcastlivestreamicon", (e) => e.bordered_live_stream_icon],
	["capsule", (e) => e.MainCapsuleImageContainer],
	["capsulecontainer", (e) => e.SeeAllLink],
	["capsuletwowidth", (e) => e.TwoWidthCtn],
	["carousel", (e) => e.pipScrollerContainer],
	["creatorhome", (e) => e.FollowBtnText],
	["creatorhomecarousel", (e) => e.CreatorHomeWithItems],
	["focusring", (e) => e.FocusRingRoot],
	["gamehover", (e) => e.GameHoverCapsuleCtn],
	["gametheater", (e) => e.TheaterModeHeader],
	["gametheaterplayer", (e) => e.TrailerPlayer],
	["gametheaterplayercontrols", (e) => e.MenuLayer],
	["gametheatersettingsmenu", (e) => e.PlaybackButton],
	["gametheaterstrip", (e) => e.StripScrollbar],
	["scrollsnapcarousel", (e) => e.ScrollSnapCarousel],
	["sidebaraccessibilityinfo", (e) => e.FeatureNameContainer],
	["sidebarcontrollerinfo", (e) => e.StoreSidebarContainer],
	["storeitemscarousel", (e) => e.StoreItemsCarousel],
	["latestupdates", (e) => e.LatestUpdateButtonCtn],
	["latestupdatescapsule", (e) => e.OtherEvents],
	["latestupdatesdate", (e) => e.DateAndTimeInline],
];
